# Generated by Django 6.1 on 2026-08-07 13:18

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sources", "0001_initial"),
    ]

    operations = [
        # Idempotent (CREATE EXTENSION IF NOT EXISTS): already enabled by
        # infra/postgres/init.sql in this project's own Postgres, but this
        # makes the migration self-contained for any other environment.
        VectorExtension(),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("index", models.PositiveIntegerField()),
                ("content", models.TextField()),
                (
                    "heading_path",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                ("start_line", models.PositiveIntegerField()),
                ("end_line", models.PositiveIntegerField()),
                ("token_count", models.PositiveIntegerField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1024, null=True
                    ),
                ),
                (
                    "search_vector",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.contrib.postgres.search.SearchVector(
                            "content", config="english"
                        ),
                        output_field=django.contrib.postgres.search.SearchVectorField(),
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="sources.document",
                    ),
                ),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="chunk_search_vector_gin"
                    ),
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="chunk_embedding_hnsw",
                        opclasses=["vector_cosine_ops"],
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "index"),
                        name="unique_chunk_index_per_document",
                    )
                ],
            },
        ),
    ]
