# Generated by Django 6.1 on 2026-08-07 16:25

import sources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0002_syncrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="original_file",
            field=models.FileField(
                blank=True, null=True, upload_to=sources.models.document_upload_path
            ),
        ),
    ]
