# Generated by Django 6.1 on 2026-08-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0003_document_original_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
