# Generated by Django 6.1 on 2026-08-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0004_source_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syncrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="running",
                max_length=20,
            ),
        ),
    ]
