# Generated by Django 6.1 on 2026-08-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rag", "0002_backfill_conversation_titles"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="citation",
            options={"ordering": ["rank"]},
        ),
        migrations.AddField(
            model_name="citation",
            name="rank",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="citation",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
