# Generated by Django 6.1 on 2026-08-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rag", "0003_alter_citation_options_citation_rank_citation_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="retrieved_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
