/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analytics/dashboard/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Read-only, same shape as core.api_views.SystemStatusView: a pure
         *     function computes the data, this just scopes it to the caller's
         *     workspaces and serializes it.
         */
        get: operations["analytics_dashboard_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Destroy is a real delete, not a soft one: a conversation carries no
         *     value once discarded, and its Messages and Citations cascade away with
         *     it. Nothing indexed is touched — Citation points at a Chunk, not the
         *     other way around, so the notes themselves are unaffected.
         */
        get: operations["conversations_list"];
        put?: never;
        /**
         * @description Destroy is a real delete, not a soft one: a conversation carries no
         *     value once discarded, and its Messages and Citations cascade away with
         *     it. Nothing indexed is touched — Citation points at a Chunk, not the
         *     other way around, so the notes themselves are unaffected.
         */
        post: operations["conversations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Destroy is a real delete, not a soft one: a conversation carries no
         *     value once discarded, and its Messages and Citations cascade away with
         *     it. Nothing indexed is touched — Citation points at a Chunk, not the
         *     other way around, so the notes themselves are unaffected.
         */
        get: operations["conversations_retrieve"];
        put?: never;
        post?: never;
        /**
         * @description Destroy is a real delete, not a soft one: a conversation carries no
         *     value once discarded, and its Messages and Citations cascade away with
         *     it. Nothing indexed is touched — Citation points at a Chunk, not the
         *     other way around, so the notes themselves are unaffected.
         */
        delete: operations["conversations_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["documents_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["documents_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/chunks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description The indexed form of one document, in order.
         *
         *     Reads through get_object(), so workspace scoping is inherited
         *     rather than re-implemented — a chunk endpoint that forgot it
         *     would leak another tenant's notes verbatim.
         */
        get: operations["documents_chunks_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/messages/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Read-only: assistant messages are only ever created by the chat
         *     orchestration in rag.chat.service.ask() (retrieval, LLM call, citation
         *     validation), never via a plain CRUD POST here.
         */
        get: operations["messages_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/messages/{message_id}/feedback/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST is idempotent here by construction, not just by convention:
         *     the same rating sent twice, or a changed one, always ends with exactly
         *     one Feedback row for this message — see Feedback.message being a
         *     OneToOneField, not a ForeignKey.
         */
        post: operations["messages_feedback_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["sources_list"];
        put?: never;
        post: operations["sources_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["sources_retrieve"];
        put: operations["sources_update"];
        post?: never;
        delete: operations["sources_destroy"];
        options?: never;
        head?: never;
        patch: operations["sources_partial_update"];
        trace?: never;
    };
    "/api/sources/{id}/cancel_sync/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sources_cancel_sync_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{id}/sync/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sources_sync_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/browse/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["sources_browse_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/status/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Read-only. Kept in DRF (unlike the plain Django auth views next
         *     door in core/views.py) so it lands in the OpenAPI schema and the SPA
         *     gets a generated type for it like every other endpoint.
         */
        get: operations["system_status_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description What was actually indexed, as the retriever sees it.
         *
         *     Deliberately exposes `content_with_heading` next to `content`: they
         *     differ for every chunk split off the middle of a section, and that
         *     difference is the whole reason the property exists. Seeing the two
         *     side by side is what makes the chunking legible instead of a black
         *     box.
         */
        Chunk: {
            /** Format: uuid */
            readonly id: string;
            readonly index: number;
            readonly heading_path: string;
            readonly start_line: number;
            readonly end_line: number;
            readonly token_count: number;
            readonly content: string;
            readonly content_with_heading: string;
            readonly embedded: boolean;
        };
        Citation: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            chunk: string;
            readonly path: string;
            readonly heading_path: string;
            readonly source_name: string;
            rank?: number;
            /** Format: double */
            score?: number | null;
            readonly start_line: number;
            readonly end_line: number;
            readonly content: string;
        };
        Conversation: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            workspace: string;
            /** Format: uuid */
            readonly user: string;
            title?: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        ConversationRequest: {
            /** Format: uuid */
            workspace: string;
            title?: string;
        };
        DailyQueryCount: {
            /** Format: date */
            date: string;
            count: number;
        };
        DashboardMetrics: {
            documents: number;
            queries_today: number;
            queries_by_day: components["schemas"]["DailyQueryCount"][];
            /** Format: double */
            cost_this_month_usd: number | null;
            latency_p50_ms: number | null;
            latency_p95_ms: number | null;
            /** Format: double */
            positive_feedback_percent: number | null;
            total_feedback: number;
            never_retrieved_documents: number;
        };
        DirectoryEntry: {
            name: string;
            path: string;
            absolute_path: string;
        };
        DirectoryListing: {
            path: string;
            parent: string | null;
            absolute_path: string;
            entries: components["schemas"]["DirectoryEntry"][];
        };
        Document: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            source: string;
            external_id: string;
            path: string;
            title?: string;
            version?: number;
            deleted?: boolean;
            metadata?: unknown;
            readonly chunk_count: number;
            readonly embedded_chunk_count: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        Feedback: {
            /** Format: uuid */
            readonly id: string;
            rating: components["schemas"]["FeedbackRatingEnum"];
            comment?: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `up` - Up
         *     * `down` - Down
         * @enum {string}
         */
        FeedbackRatingEnum: "up" | "down";
        FeedbackRequest: {
            rating: components["schemas"]["FeedbackRatingEnum"];
            comment?: string;
        };
        Message: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            conversation: string;
            role: components["schemas"]["RoleEnum"];
            content: string;
            latency_ms?: number | null;
            input_tokens?: number | null;
            output_tokens?: number | null;
            /** Format: decimal */
            cost?: string | null;
            retrieved_count?: number;
            readonly citations: components["schemas"]["Citation"][];
            readonly feedback: components["schemas"]["MessageFeedback"] | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description Describes the *shape* of MessageSerializer.feedback for the OpenAPI
         *     schema only — never instantiated to validate or save anything (that's
         *     analytics.serializers.FeedbackSerializer's job). Defined here, not
         *     imported from there, so the generated TS type is `{ rating; comment }
         *     | null` instead of a generic string-keyed object, without giving `rag`
         *     an import from `analytics`.
         */
        MessageFeedback: {
            rating: components["schemas"]["MessageFeedbackRatingEnum"];
            comment: string;
        };
        /**
         * @description * `up` - up
         *     * `down` - down
         * @enum {string}
         */
        MessageFeedbackRatingEnum: "up" | "down";
        PaginatedChunkList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Chunk"][];
        };
        PaginatedConversationList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Conversation"][];
        };
        PaginatedDocumentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Document"][];
        };
        PaginatedMessageList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Message"][];
        };
        PaginatedSourceList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Source"][];
        };
        PatchedSourceRequest: {
            /** Format: uuid */
            workspace?: string;
            name?: string;
            type?: components["schemas"]["TypeEnum"];
            config?: unknown;
            enabled?: boolean;
        };
        ProviderStatus: {
            provider: string;
            model: string;
        };
        /**
         * @description * `user` - User
         *     * `assistant` - Assistant
         * @enum {string}
         */
        RoleEnum: "user" | "assistant";
        Source: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            workspace: string;
            name: string;
            type: components["schemas"]["TypeEnum"];
            config?: unknown;
            readonly status: components["schemas"]["StatusEnum"];
            enabled?: boolean;
            readonly chunk_count: number;
            readonly embedded_chunk_count: number;
            /** Format: date-time */
            readonly last_synced_at: string | null;
            readonly last_error: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        SourceRequest: {
            /** Format: uuid */
            workspace: string;
            name: string;
            type: components["schemas"]["TypeEnum"];
            config?: unknown;
            enabled?: boolean;
        };
        /**
         * @description * `pending` - Pending
         *     * `syncing` - Syncing
         *     * `ready` - Ready
         *     * `error` - Error
         * @enum {string}
         */
        StatusEnum: "pending" | "syncing" | "ready" | "error";
        SyncQueued: {
            status: string;
        };
        SystemStatus: {
            embedding: components["schemas"]["ProviderStatus"];
            reranking: components["schemas"]["ProviderStatus"];
            llm: components["schemas"]["ProviderStatus"];
            embedding_dimensions: number;
            retrieval_strategy: string;
            sources: number;
            documents: number;
            chunks: number;
            embedded_chunks: number;
            answers: number;
            avg_latency_ms: number | null;
            /** Format: double */
            avg_citations_per_answer: number | null;
            ungrounded_answers: number;
            using_fake_providers: boolean;
        };
        /**
         * @description * `local_folder` - Local folder
         *     * `github` - GitHub
         * @enum {string}
         */
        TypeEnum: "local_folder" | "github";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analytics_dashboard_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardMetrics"];
                };
            };
        };
    };
    conversations_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedConversationList"];
                };
            };
        };
    };
    conversations_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ConversationRequest"];
                "multipart/form-data": components["schemas"]["ConversationRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
        };
    };
    conversations_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this conversation. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
        };
    };
    conversations_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this conversation. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    documents_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Filter documents down to a single source. */
                source?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDocumentList"];
                };
            };
        };
    };
    documents_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this document. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    documents_chunks_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                /** @description A UUID string identifying this document. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedChunkList"];
                };
            };
        };
    };
    messages_list: {
        parameters: {
            query?: {
                /** @description Filter messages down to a single conversation. */
                conversation?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMessageList"];
                };
            };
        };
    };
    messages_feedback_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["FeedbackRequest"];
                "multipart/form-data": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feedback"];
                };
            };
        };
    };
    sources_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSourceList"];
                };
            };
        };
    };
    sources_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SourceRequest"];
                "multipart/form-data": components["schemas"]["SourceRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
        };
    };
    sources_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this source. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
        };
    };
    sources_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this source. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SourceRequest"];
                "multipart/form-data": components["schemas"]["SourceRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
        };
    };
    sources_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this source. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sources_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this source. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSourceRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSourceRequest"];
                "multipart/form-data": components["schemas"]["PatchedSourceRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
        };
    };
    sources_cancel_sync_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this source. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncQueued"];
                };
            };
        };
    };
    sources_sync_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this source. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncQueued"];
                };
            };
        };
    };
    sources_browse_retrieve: {
        parameters: {
            query?: {
                path?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryListing"];
                };
            };
        };
    };
    system_status_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
        };
    };
}
